import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeContextProvider } from "@/context/themeContext";
import { CssBaseline } from "@mui/material";
import AppLayout from "./app";
import Head from "next/head";
import { NotificationProvider } from "@/components/notificationProvider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Restaurant Management",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <link rel="icon" href="public/favicon.ico" />
            </Head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ThemeContextProvider>
                    <CssBaseline />
                    <AppLayout >
                        <NotificationProvider >
                            {children}
                        </NotificationProvider>
                    </AppLayout>
                </ThemeContextProvider>
            </body>
        </html>
    );
}
